on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: npm ci
        uses: actions/npm@v2
        with:
          args: ci
      - name: npm lint
        uses: actions/npm@v2
        with:
          args: run lint
      - name: npm test
        uses: actions/npm@v2
        with:
          args: run test