name: On Push workflow

on:
  push:
    branches:
      - master
      - develop
      - 'releases/**'
    tags:
      - v1
env:
  NODE_VERSION: 8.x

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Uses Node.js version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          npm ci
          npm test
