name: PR workflow

on:
  pull_request:
    branches: [master, develop]
env:
  NODE_VERSION: 8.x
jobs:
  build_and_test:
    runs-on: ["ubuntu-latest","windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - name: Uses Node.js version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          npm ci
          npm test
