name: PR workflow

on:
  pull_request:
    branches: [master, develop]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [8,x,10.x,12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Uses Node.js version ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - run: |
        npm ci
        npm test